{{- $fullName := include "php.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "php.labels" . | nindent 4 }}
spec:
  rules:
    - http:
        paths:
          - path: {{ .Values.url }}
            backend:
              serviceName: {{ $fullName }}
              servicePort: {{ $svcPort }}
